apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.secrets.db_host | b64enc }}
  DB_USER: {{ .Values.secrets.db_user | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.db_password | b64enc }}
  DB_NAME: {{ .Values.secrets.db_name | b64enc }}
  SECRET_KEY: {{ .Values.secrets.secret_key | b64enc }}
  EMAIL_PASSWORD: {{ .Values.secrets.email_password | b64enc }}
